# https://github.com/Homebrew/homebrew-bundle

# Homebrew
# https://github.com/Homebrew/brew/

brew "openssl"
brew "bat"

# homebrew-cask
# https://github.com/Homebrew/homebrew-cask

cask "slack"

# vim: set filetype=ruby: