#!/bin/bash

# Based on https://github.com/matchai/dotfiles

{ # Prevent script from running if partially downloaded

sudo_prompt() {
  echo "Please enter your password for sudo authentication"
  sudo -k
  sudo echo "sudo authenticaion successful!"
  while true ; do sudo -n true ; sleep 60 ; kill -0 "$$" || exit ; done 2>/dev/null &
}

install_command_line_tools() {
  # Unattended installation of Command Line Tools
  # Found on apple.stackexchange.com at https://apple.stackexchange.com/questions/107307/how-can-i-install-the-command-line-tools-completely-from-the-command-line/195963#195963
  # Homebrew uses a similar technique https://github.com/Homebrew/install/blob/878b5a18b89ff73f2f221392ecaabd03c1e69c3f/install#L297
  xcode-select -p >/dev/null || {
    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    CLT=$( softwareupdate -l |
      grep "\*.*Command Line Tools" |
      head -n 1 |
      awk -F ":" '{print $2}' |
      sed -e 's/^ *//' |
      tr -d '\n' )
    softwareupdate -i "$CLT" --verbose
    rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
  }
  echo "Command Line Tools are installed at $(xcode-select -p)"
}

set_initial_hostname() {
  # On a new macbook HostName is not set by default
  # If it's been set already we can skip this step
  if [ -n "$(scutil --get HostName)" ]; then
    echo "Hostname is already set to $(scutil --get HostName)... continuing ..."
    return
  fi

  # Ask for hostname
  echo "What would you like your hostname to be?"
  read -r hostname

  # Set the hostname
  sudo scutil --set ComputerName "$hostname"
  sudo scutil --set HostName "$hostname"
  sudo scutil --set LocalHostName "$hostname"

  echo "Hostname set to $hostname, please rerun this script in a new terminal to continue installation."
  exit
}

install_nix() {
  command -v nix >/dev/null || {
    sh <(curl -L https://nixos.org/nix/install)
  }

  # Create the configuration directory
  mkdir -p ~/.config/nix

  # Configuration to be added that enables flakes
  config_line="experimental-features = nix-command flakes"

   # Path to the Nix configuration file
  nix_config_file=~/.config/nix/nix.conf

  # Check if the configuration line already exists; append if not
  if ! grep -qF -- "$config_line" "$nix_config_file"; then
    echo "$config_line" >> "$nix_config_file"
  fi
}

clone_repository() {
  repository="https://github.com/aaronjbaptiste/dotfiles.git"
  clone_target="${HOME}/.dotfiles"
  if grep -q "${repository}" "${clone_target}/.git/config"; then
    cd "${clone_target}" || exit
    git status
    git pull
    cd - || exit
  else
    rm -rf "${clone_target}"
    git clone "${repository}" "${clone_target}"
  fi
}

darwin_build() {
  command -v darwin-rebuild >/dev/null || {
    # Install nix-darwin
    nix run nix-darwin -- switch --flake "$HOME/dotfiles"
  }

  # Apply the configuration
  darwin-rebuild switch --flake "$HOME/dotfiles"
}

# Installation flow
sudo_prompt
install_command_line_tools
set_initial_hostname
install_nix
clone_repository
darwin_build

} # Prevent script from running if partially downloaded