#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config focus_follows_mouse autoraise
yabai -m config window_placement first_child
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xFF6faec0
yabai -m config normal_window_border_color 0xFF3e4050
yabai -m config insert_feedback_color 0xffff6e6e
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config window_animation_duration 0
yabai -m config window_border_radius 11

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 41
yabai -m config bottom_padding 17
yabai -m config left_padding 17
yabai -m config right_padding 17
yabai -m config window_gap 12
#yabai -m config external_bar all:28:0

yabai -m rule --add app="^(Calculator|System Preferences|Photo Booth|Archive Utility|Color Picker|.*Legends.*)$" manage=off

yabai -m space 1 --label Code
yabai -m space 2 --label Text
yabai -m space 3 --label Web
yabai -m space 4 --label Idle
yabai -m space 5 --label Misc
yabai -m space 6 --label doc
yabai -m space 7 --label help
yabai -m space 8 --label music

### Sketchybar ###
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

echo "yabai configuration loaded.."
