#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                                 \
    external_bar                 all:34:0       \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          off            \
    window_topmost               off            \
    window_shadow                off            \
    window_animation_duration    0              \
    window_animation_frame_rate  120            \
    window_opacity_duration      0              \
    active_window_opacity        1.00           \
    normal_window_opacity        0.85           \
    window_opacity               on             \
    insert_feedback_color        0x551F1F28     \
    active_window_border_color   0x751F1F28     \
    normal_window_border_color   0x451F1F28     \
    window_border_width          1              \
    window_border_radius         11             \
    window_border_blur           on             \
    window_border_hidpi          off            \
    window_border                on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   8              \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# shellcheck disable=SC3030
yabai_apps=(
  "Calendar"
  "Finder"
  "Google Chrome"
  "Mail"
  "Notes"
  "Slack"
  "kitty"
)

YABAI_APPS_REGEX="$(
  IFS=\|
  # shellcheck disable=SC3054
  echo "${yabai_apps[*]}"
)"

# whitelist strategy
yabai -m rule --add app!="${YABAI_APPS_REGEX}" manage=off

echo "$(date '+%F %T%z') yabai configuration loaded"
