# Configured to run alongside marksman.
[[language]]
auto-format = true
language-servers = ["marksman", "mpls"]
name = "markdown"

[[language]]
name = "html"
roots = [".git"]
language-servers = ["emmet-lsp"]

[language-server.mpls]
command = "mpls"
args = ["--dark-mode", "--enable-emoji"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.typescript-language-server]
command = "/Users/aaronjb/.npm-global/bin/typescript-language-server"
args = ["--stdio"]

[language-server.tsgo]
command = "/Users/aaronjb/.npm-global/bin/tsc"
args = ["--lsp", "--stdio"]
timeout = 120

[[language]]
name = "typescript"
language-servers = ["tsgo", "typescript-language-server"]

[[language]]
name = "tsx"
language-servers = ["tsgo", "typescript-language-server"]

[[language]]
name = "javascript"
language-servers = ["tsgo", "typescript-language-server"]

[[language]]
name = "jsx"
language-servers = ["tsgo", "typescript-language-server"]
